[build]
  publish = "public"
  command = "npm run build"

# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/


[[redirects]]
  from = "/"
  to = "/nl-BE/"
  status = 200
  conditions = {Language = ["nl"]}

[[redirects]]
  from = "/"
  to = "/tr-TR/"
  status = 200
  conditions = {Language = ["tr"]}

# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/en-GB/"
  status = 200

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/tr-TR/:splat"
  status = 302
  conditions = {Language = ["tr"]}

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/nl-BE/:splat"
  status = 302
  conditions = {Language = ["nl"]}

# Default
[[redirects]]
  from = "/*"
  to = "/en-GB/:splat"
  status = 302

[[redirects]]
  from = "/admin"
  to = "/admin:splat"
  force = true
  status = 200
  conditions = {Role = ["admin"]}

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

# The default HTTP status code is 301, but you can define a different one e.g.
# status = 302

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
